apiVersion: apps/v1
kind: Deployment
metadata:
  name: somelse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: somelse
  template:
    metadata:
      labels:
        app: somelse
    spec:
      containers:
      - image: okteto.dev/somelse:latest
        name: somelse
        ports:
        - containerPort: 8080
