apiVersion: v1
kind: Service
metadata:
  name: somelse
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "somelse"
    port: 8080
  selector:
    app: somelse
